import {colorWithOpacity as u, cssRender, Palette, css} from '../../utils'

export const MdRefPaletteError0 = '#000000' // Error 0
export const MdRefPaletteError10 = '#410e0b' // Error 10
export const MdRefPaletteError20 = '#601410' // Error 20
export const MdRefPaletteError30 = '#8c1d18' // Error 30
export const MdRefPaletteError40 = '#b3261e' // Error 40
export const MdRefPaletteError50 = '#dc362e' // Error 50
export const MdRefPaletteError60 = '#e46962' // Error 60
export const MdRefPaletteError70 = '#ec928e' // Error 70
export const MdRefPaletteError80 = '#f2b8b5' // Error 80
export const MdRefPaletteError90 = '#f9dedc' // Error 90
export const MdRefPaletteError95 = '#fceeee' // Error 95
export const MdRefPaletteError99 = '#fffbf9' // Error 99
export const MdRefPaletteError100 = '#ffffff' // Error 100
export const MdRefPaletteTertiary0 = '#000000' // Tertiary 0
export const MdRefPaletteTertiary10 = '#31111d' // Tertiary 10
export const MdRefPaletteTertiary20 = '#492532' // Tertiary 20
export const MdRefPaletteTertiary30 = '#633b48' // Tertiary 30
export const MdRefPaletteTertiary40 = '#7d5260' // Tertiary 40
export const MdRefPaletteTertiary50 = '#986977' // Tertiary 50
export const MdRefPaletteTertiary60 = '#b58392' // Tertiary 60
export const MdRefPaletteTertiary70 = '#d29dac' // Tertiary 70
export const MdRefPaletteTertiary80 = '#efb8c8' // Tertiary 80
export const MdRefPaletteTertiary90 = '#ffd8e4' // Tertiary 90
export const MdRefPaletteTertiary95 = '#ffecf1' // Tertiary 95
export const MdRefPaletteTertiary99 = '#fffbfa' // Tertiary 99
export const MdRefPaletteTertiary100 = '#ffffff' // Tertiary 100
export const MdRefPaletteSecondary0 = '#000000' // Secondary 0
export const MdRefPaletteSecondary10 = '#1d192b' // Secondary 10
export const MdRefPaletteSecondary20 = '#332d41' // Secondary 20
export const MdRefPaletteSecondary30 = '#4a4458' // Secondary 30
export const MdRefPaletteSecondary40 = '#625b71' // Secondary 40
export const MdRefPaletteSecondary50 = '#7a7289' // Secondary 50
export const MdRefPaletteSecondary60 = '#958da5' // Secondary 60
export const MdRefPaletteSecondary70 = '#b0a7c0' // Secondary 70
export const MdRefPaletteSecondary80 = '#ccc2dc' // Secondary 80
export const MdRefPaletteSecondary90 = '#e8def8' // Secondary 90
export const MdRefPaletteSecondary95 = '#f6edff' // Secondary 95
export const MdRefPaletteSecondary99 = '#fffbfe' // Secondary 99
export const MdRefPaletteSecondary100 = '#ffffff' // Secondary 100
export const MdRefPalettePrimary0 = '#000000' // Primary 0
export const MdRefPalettePrimary10 = '#21005d' // Primary 10
export const MdRefPalettePrimary20 = '#381e72' // Primary 20
export const MdRefPalettePrimary30 = '#4f378b' // Primary 30
export const MdRefPalettePrimary40 = '#6750a4' // Primary 40
export const MdRefPalettePrimary50 = '#7f67be' // Primary 50
export const MdRefPalettePrimary60 = '#9a82db' // Primary 60
export const MdRefPalettePrimary70 = '#b69df8' // Primary 70
export const MdRefPalettePrimary80 = '#d0bcff' // Primary 80
export const MdRefPalettePrimary90 = '#eaddff' // Primary 90
export const MdRefPalettePrimary95 = '#f6edff' // Primary 95
export const MdRefPalettePrimary99 = '#fffbfe' // Primary 99
export const MdRefPalettePrimary100 = '#ffffff' // Primary 100
export const MdRefPaletteNeutralVariant0 = '#000000' // Neutral Variant 0
export const MdRefPaletteNeutralVariant10 = '#1d1a22' // Neutral Variant 10
export const MdRefPaletteNeutralVariant20 = '#322f37' // Neutral Variant 20
export const MdRefPaletteNeutralVariant30 = '#49454f' // Neutral Variant 30
export const MdRefPaletteNeutralVariant40 = '#605d66' // Neutral Variant 40
export const MdRefPaletteNeutralVariant50 = '#79747e' // Neutral Variant 50
export const MdRefPaletteNeutralVariant60 = '#938f99' // Neutral Variant 60
export const MdRefPaletteNeutralVariant70 = '#aea9b4' // Neutral Variant 70
export const MdRefPaletteNeutralVariant80 = '#cac4d0' // Neutral Variant 80
export const MdRefPaletteNeutralVariant90 = '#e7e0ec' // Neutral Variant 90
export const MdRefPaletteNeutralVariant95 = '#f5eefa' // Neutral Variant 95
export const MdRefPaletteNeutralVariant99 = '#fffbfe' // Neutral Variant 99
export const MdRefPaletteNeutralVariant100 = '#ffffff' // Neutral Variant 100
export const MdRefPaletteNeutral0 = '#000000' // Neutral 0
export const MdRefPaletteNeutral10 = '#1c1b1f' // Neutral 10
export const MdRefPaletteNeutral20 = '#313033' // Neutral 20
export const MdRefPaletteNeutral30 = '#484649' // Neutral 30
export const MdRefPaletteNeutral40 = '#605d62' // Neutral 40
export const MdRefPaletteNeutral50 = '#787579' // Neutral 50
export const MdRefPaletteNeutral60 = '#939094' // Neutral 60
export const MdRefPaletteNeutral70 = '#aeaaae' // Neutral 70
export const MdRefPaletteNeutral80 = '#c9c5ca' // Neutral 80
export const MdRefPaletteNeutral90 = '#e6e1e5' // Neutral 90
export const MdRefPaletteNeutral95 = '#f4eff4' // Neutral 95
export const MdRefPaletteNeutral99 = '#fffbfe' // Neutral 99
export const MdRefPaletteNeutral100 = '#ffffff' // Neutral 100
export const MdRefPaletteBlack = '#000000' // Black
export const MdRefPaletteWhite = '#ffffff' // White

export const palette: Palette = {
  error0: (o) => u(MdRefPaletteError0, o),
  error10: (o) => u(MdRefPaletteError10, o),
  error20: (o) => u(MdRefPaletteError20, o),
  error30: (o) => u(MdRefPaletteError30, o),
  error40: (o) => u(MdRefPaletteError40, o),
  error50: (o) => u(MdRefPaletteError50, o),
  error60: (o) => u(MdRefPaletteError60, o),
  error70: (o) => u(MdRefPaletteError70, o),
  error80: (o) => u(MdRefPaletteError80, o),
  error90: (o) => u(MdRefPaletteError90, o),
  error95: (o) => u(MdRefPaletteError95, o),
  error99: (o) => u(MdRefPaletteError99, o),
  error100: (o) => u(MdRefPaletteError100, o),
  tertiary0: (o) => u(MdRefPaletteTertiary0, o),
  tertiary10: (o) => u(MdRefPaletteTertiary10, o),
  tertiary20: (o) => u(MdRefPaletteTertiary20, o),
  tertiary30: (o) => u(MdRefPaletteTertiary30, o),
  tertiary40: (o) => u(MdRefPaletteTertiary40, o),
  tertiary50: (o) => u(MdRefPaletteTertiary50, o),
  tertiary60: (o) => u(MdRefPaletteTertiary60, o),
  tertiary70: (o) => u(MdRefPaletteTertiary70, o),
  tertiary80: (o) => u(MdRefPaletteTertiary80, o),
  tertiary90: (o) => u(MdRefPaletteTertiary90, o),
  tertiary95: (o) => u(MdRefPaletteTertiary95, o),
  tertiary99: (o) => u(MdRefPaletteTertiary99, o),
  tertiary100: (o) => u(MdRefPaletteTertiary100, o),
  secondary0: (o) => u(MdRefPaletteSecondary0, o),
  secondary10: (o) => u(MdRefPaletteSecondary10, o),
  secondary20: (o) => u(MdRefPaletteSecondary20, o),
  secondary30: (o) => u(MdRefPaletteSecondary30, o),
  secondary40: (o) => u(MdRefPaletteSecondary40, o),
  secondary50: (o) => u(MdRefPaletteSecondary50, o),
  secondary60: (o) => u(MdRefPaletteSecondary60, o),
  secondary70: (o) => u(MdRefPaletteSecondary70, o),
  secondary80: (o) => u(MdRefPaletteSecondary80, o),
  secondary90: (o) => u(MdRefPaletteSecondary90, o),
  secondary95: (o) => u(MdRefPaletteSecondary95, o),
  secondary99: (o) => u(MdRefPaletteSecondary99, o),
  secondary100: (o) => u(MdRefPaletteSecondary100, o),
  primary0: (o) => u(MdRefPalettePrimary0, o),
  primary10: (o) => u(MdRefPalettePrimary10, o),
  primary20: (o) => u(MdRefPalettePrimary20, o),
  primary30: (o) => u(MdRefPalettePrimary30, o),
  primary40: (o) => u(MdRefPalettePrimary40, o),
  primary50: (o) => u(MdRefPalettePrimary50, o),
  primary60: (o) => u(MdRefPalettePrimary60, o),
  primary70: (o) => u(MdRefPalettePrimary70, o),
  primary80: (o) => u(MdRefPalettePrimary80, o),
  primary90: (o) => u(MdRefPalettePrimary90, o),
  primary95: (o) => u(MdRefPalettePrimary95, o),
  primary99: (o) => u(MdRefPalettePrimary99, o),
  primary100: (o) => u(MdRefPalettePrimary100, o),
  neutralVariant0: (o) => u(MdRefPaletteNeutralVariant0, o),
  neutralVariant10: (o) => u(MdRefPaletteNeutralVariant10, o),
  neutralVariant20: (o) => u(MdRefPaletteNeutralVariant20, o),
  neutralVariant30: (o) => u(MdRefPaletteNeutralVariant30, o),
  neutralVariant40: (o) => u(MdRefPaletteNeutralVariant40, o),
  neutralVariant50: (o) => u(MdRefPaletteNeutralVariant50, o),
  neutralVariant60: (o) => u(MdRefPaletteNeutralVariant60, o),
  neutralVariant70: (o) => u(MdRefPaletteNeutralVariant70, o),
  neutralVariant80: (o) => u(MdRefPaletteNeutralVariant80, o),
  neutralVariant90: (o) => u(MdRefPaletteNeutralVariant90, o),
  neutralVariant95: (o) => u(MdRefPaletteNeutralVariant95, o),
  neutralVariant99: (o) => u(MdRefPaletteNeutralVariant99, o),
  neutralVariant100: (o) => u(MdRefPaletteNeutralVariant100, o),
  neutral0: (o) => u(MdRefPaletteNeutral0, o),
  neutral10: (o) => u(MdRefPaletteNeutral10, o),
  neutral20: (o) => u(MdRefPaletteNeutral20, o),
  neutral30: (o) => u(MdRefPaletteNeutral30, o),
  neutral40: (o) => u(MdRefPaletteNeutral40, o),
  neutral50: (o) => u(MdRefPaletteNeutral50, o),
  neutral60: (o) => u(MdRefPaletteNeutral60, o),
  neutral70: (o) => u(MdRefPaletteNeutral70, o),
  neutral80: (o) => u(MdRefPaletteNeutral80, o),
  neutral90: (o) => u(MdRefPaletteNeutral90, o),
  neutral95: (o) => u(MdRefPaletteNeutral95, o),
  neutral99: (o) => u(MdRefPaletteNeutral99, o),
  neutral100: (o) => u(MdRefPaletteNeutral100, o),
  black: (o) => u(MdRefPaletteBlack, o),
  white: (o) => u(MdRefPaletteWhite, o),

  [css]: function () {
    return cssRender(this, '--md-ref-palette')
  },
}
